### ISSUE TITLE
Limit buffering of cache missed responses

### ISSUE THREAD

**Issue by willscott** [filecoin-saturn/L1-node#308]
> saturn nginx is not configured with proxy buffering off. This means that NGINX on Saturn will wait to get the whole response from the shim/Lassie before sending it back to the gateway. Is this intended? 

https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/#configuring-buffers

**Comment by hannahhoward** [comment]
I'll admit while the above text does seem to indicate holding the whole response, others make it seem very unclear. I'm honestly perplexed and anyway caching is completely disabled by proxy_buffering off so that seems untenable. that said, it would be helpful to direct test TTFB on Saturn + Lassie from a client like ARC.

**Comment by guanzo** [comment]
>  caching is completely disabled by proxy_buffering off so that seems untenable

can confirm. Not sure if we can proceed here.

**Comment by willscott** [comment]
we've confirmed at this point that cache misses do stream.
