### ISSUE TITLE
mirror grafana dashboard for test net

### ISSUE THREAD

**Issue by gruns** [filecoin-saturn/L1-node#63]
once http3 has landed in the test network (https://github.com/filecoin-saturn/L1-node/issues/42):

* mirror the production grafana (https://protocollabs.grafana.net/d/_l58mGiVz/saturn-aggregated-metrics?orgId=1&refresh=1h)

* mirror grafana in such a way as to avoid future copy+pasta. in other words, when we push a change to grafana, that change should be reflected in both the prod and test grafana dashboards without further user action

    what we want to avoid is manual copy+pasta+deploy to mirror prod and test manually with every change ad nauseum into the future
    
@AmeanAsad what's the best way to bundle the two dashboards together? ideally they both live under the same url just in different tabs. but bc grafana doesnt have tabs, what's the next best thing? 

what we want to avoid is two different grafana urls to remember, one for prod and one for test

**Comment by AmeanAsad** [comment]
As tabs are a not available in Grafana, the next viable option is just to have a variable in a dropdown that changes the table name we're querying. 

If the test data is in another Database though, then this might be difficult, as we would have to change the actual data source we're querying from, and I do not think there is a programmatic way to change that in Grafana based on some external variable.

**Comment by AmeanAsad** [comment]
@gruns 

I looked into the options we have to bundle the two dashboards together. 

1. **Same code, change the data source**:
   This involves setting a dynamic variable that changes the data source for our query (one data source for test and one for prod). There are a view issues with this though:
- The graphs for test net and prod have to be identical. If we want to test something new on the test net and make a custom graph to monitor it (which is likely to happen), unless the graph is also available on prod, the dashboard will error out. 
- The SQL for both graphs have to be identical. This means we have to setup data aggregation for the test net as well. Currently we do not need to aggregate data on the test net because the load isn't that much so we'd be introducing more tables and more code that is not necessary. 

2. **Using  Plugins**:
The idea of being able to switch dashboards through tabs has been an ongoing issue. Their solution to this was creating [dashboard folders](https://github.com/grafana/grafana/issues/322). The only alternative that offers  tabs are user made custom plugins. I don't want to introduce custom plugins into our code base just to have tabs. The complexity of integrating a user made plugin is more than just managing two dashboards. 


With the consideration of the above options, I still think we should split the two dashboards at least until we are through with the lisbon launch. The first option constraints us too much in my opinion by coupling prod and test graphs. Also, I'd argue it is more work and code to setup data aggregation for another data source vs just maintaining another dashboard for launch. 

Gonna CC @DiegoRBaquero @guanzo here as well if they have any opinions on this issue as they are avid users of the dashboard.

**Comment by guanzo** [comment]
Go with what's easiest imo. I don't mind 2 separate dashboards with 2 different URLs. Just bookmark both and call it a day.

**Comment by gruns** [comment]
great homework, @AmeanAsad 🙌 

ideally we dont have two independent, different, disconnected dashboards -- one for test and one for prod -- bookmarks or not

that said, this is *not* worth serious effort before lisbon. merging both dashboards in any sane way can absolutely, and should absolutely, be punted until after lisbon

in the mean time, let's

  * implement both dashboards independently
  * is it possible to insert arbitrary links into grafana? if so, link from one to the other so one only needs to remember/bookmark one URL

this comment mentions `dashboard rows`, too, in addition to dashboard folders

  * https://github.com/grafana/grafana/issues/322#issuecomment-364498385
  
whatever those are. though it is funny to see 10 trillion people ask for tabs and them not implement it. oh well; 'pull requests welcome' 😊

**Comment by AmeanAsad** [comment]
A testnet dashboard is finally here: https://protocollabs.grafana.net/d/HODTGbAVz/saturn-testnet-metrics?from=now-6h&to=now

@gruns Getting back to the thread above:
for now, there isn't enough tooling in grafana to implement a tabbed view to place two dashboards in the same view. For now I have just created a separate one and we can look into merging the two once better tooling arises or if that becomes a high priority item.
